---
title: "Midterm Exam Question 3"
subtitle: "STAT 242-02: Intermediate Statistics"
output: pdf_document
---

## A (Science Fiction) Study of the Humanoid Inhabitants of the Moon Europa

The year is 2222. Humans have satellites in orbit around Europa, the smallest of Jupiter's four moons. Satellite images have revealed the presence of a small, humanoid race of beings living on the moon's surface. Due to their small stature, it is difficult to gather data on these beings. It also has been observed that each humanoid is accompanied by an animal companion which is much larger and is vibrantly colored (red, blue, green, or orange). The size and bright coloring of these creatures makes them much easier to identify. Because it is much easier to collect data on the animal companions, scientists are anxious to learn more about these animals and to determine whether they can use this information to learn about the humanoid inhabitants. They have enlisted you as the statistical expert on this project, and have put together a number of questions to which they need answers. They have managed to collect data on 200 distinct humanoids and their (200) companion animals, which they have compiled for you in the data set `europa_df`, which contains the following variables:

- `humanoid_height`: the height of the humanoid, measured in centimeters
- `pet_height`: the height of an animal companion, measured in centimeters
- `pet_color`: color of the pet; one of blue, red, green, or orange
- `pet_temp`: body surface temperature of the animal companion, measured in degrees Celsius

```{r message=FALSE, warning=FALSE}
library(car)
library(dplyr)
library(ggplot2)
library(gmodels)
library(GGally)
library(readr)

europa_df <- read_csv("https://marievozanne.github.io/europa_df.csv")
```

### After some extensive examination of the relationships between companion color, body surface temperature, and height, the researchers have moved on to their main investigation. Recall that due to the stature of Europa's humanoid occupants, they are difficult to identify on satellites, so gathering information on them directly is challenging. Scientists familiar with the project hypothesize that attributes of the animal companions can be used estimate height for the humanoid counterparts. Specifically, they are interested in investigating the relationship between the animal color and the height of the human counterpart. They wish to compare all pairwise differences in humanoid heights for the four animal companion colors.

#### (a) What are the pairwise comparisons that the researchers wish to investigate? Define notation and write down the hypotheses for all of the pairwise comparisons that will be investigated (in proper notation).



#### (b) Assess whether the assumptions are met to perform the hypothesis tests in (a). Make any necessary transformations to the data so that you will be able to proceed with the tests.



#### (c) Conduct the hypothesis tests based on your answers in (a) and (b). Show all your work and justify your approach. Be sure to draw your conclusions in the context of the problem.



#### (d) Summarize the results from (c) in a way that is easily understandable to your collaborators. You may want to highlight any key findings.

